### ISSUE TITLE
Extend connector download to support maven artifacts directly.

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-k8s-operator#57]
The operator now supports download of additional connectors via a url/filename pair under 'Libraries' in the CR.
```
             libraries:
                description: Extra Libraries to be added to classpath. These are downloaded
                  during initialization. For more security use a custom container
                  image with these already present.
                items:
                  description: AdditionalDownloads - to define extra files to be downloaded
                  properties:
                    filename:
                      type: string
                    url:
                      type: string
                  type: object
                maxItems: 253
                minItems: 1
                type: array
```

This could be extended to support the retrieval of maven artifacts directly.

Whilst files are useful, and flexible, we do provide all of our egeria connectors as maen artifacts, and being able to simply specify a version & maven coordinate could make specification easier than composing an obscure URL

Usability improvement...
